--- #YAML:1.0
name:                Linux-DVB-DVBT-TS
version:             0.03
abstract:            Transport Stream utilities 
license:             ~
author:              
    - Steve Price <cpan@sdprice.plus.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    File::Basename:                0
    File::Path:                    0
    File::Spec:                    0
    Pod::Coverage:                 0.18
    POSIX:                         0
    Test::Pod:                     1.22
    Test::Pod::Coverage:           1.08
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
